name: Fitness Tracker Deploy

on: 
  push:
    branches:
      - "main"
  pull_request: 
    branches:
      - "main"

env:
  USER_NAME: sonali-shah
  USER_EMAIL: sonusukhadia@gmail.com
  GITHUB_TOKEN: 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
  REPO_NAME: fitness_tracker

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16]

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: setup git config
        run: |
          git config user.name $(USER_NAME)
          git config user.email $(USER_EMAIL)

      - name: setup deployment
        run: |
          npm install
          git checkout main
          rm -rf dist
          npm run build
          git add dist -f
          git commit -m "build files from github action"
          git push https://$(GITHUB_TOKEN)@github.com/$(USER_NAME)/$(REPO_NAME).git -f