name: Fitness Tracker Deploy

on: 
  push:
    branches:
      - "main"
  pull_request: 
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16]

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: setup git config
        run: |
          git config user.name "Sonali Ronak Shah"
          git config user.email "sonali.shah@gmx.de"

      - name: setup deployment
        run: |
          npm install
          git checkout main
          rm -rf dist
          npm run build
          git add dist -f
          git commit -m "build files from github action"
          git push